name: build
on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposotory
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build demo application
        run: npm run ex:build
        